<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="CK.Cris.Executor.Engine" Version="2.0.1-0.nunit-5.0.ci.1" />
        <PackageReference Include="CK.Poco.Exc.Json.Engine" Version="35.0.1-0.nunit-5.0.ci.1" />
        <PackageReference Include="CK.Testing.StObjEngine" Version="35.0.1-0.nunit-5.0.ci.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CK.AppIdentity.Cris\CK.AppIdentity.Cris.csproj" />
        <ProjectReference Include="..\CK.Testing.AppIdentity.TransportLayer\CK.Testing.AppIdentity.TransportLayer.csproj" />
    </ItemGroup>

</Project>
