<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Description>Application identity core abstraction and implementation.</Description>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="CK.Monitoring.Hosting" Version="18.0.3--0026-develop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CK.AppIdentity\CK.AppIdentity.csproj" />
  </ItemGroup>

</Project>
