using CK.Core;
using System;
using System.Security.Cryptography;

namespace CK.AppIdentity.KeyManagement;

/// <summary>
/// Encapsulates a <see cref="Nonce"/> and a <see cref="CreationTime"/> in UTC time.
/// </summary>
public readonly struct TimedNonce
{
    /// <summary>
    /// Initializes a new timed nonce.
    /// </summary>
    /// <param name="time">The creation time of the nonce. Should be <see cref="DateTimeKind.Utc"/> but no check is done here.</param>
    /// <param name="nonce">The nonce. Should be generated by a <see cref="RandomNumberGenerator"/>.</param>
    public TimedNonce( DateTime time, ulong nonce )
    {
        CreationTime = time;
        Nonce = nonce;
    }

    /// <summary>
    /// The creation time of the nonce.
    /// </summary>
    public readonly DateTime CreationTime;

    /// <summary>
    /// The nonce random value.
    /// </summary>
    public readonly ulong Nonce;

    /// <summary>
    /// Creates a new timed nonce.
    /// </summary>
    /// <param name="clock">The system clock to use.</param>
    /// <returns>A timed nonce.</returns>
    public static TimedNonce Create( ISystemClock clock )
    {
        Throw.CheckNotNullArgument( clock );
        Span<byte> bNonce = stackalloc byte[8];
        RandomNumberGenerator.Fill( bNonce );
        return new TimedNonce( clock.UtcNow, BitConverter.ToUInt64( bNonce ) );
    }

    /// <summary>
    /// Checks that the <see cref="CreationTime"/> is <see cref="DateTimeKind.Utc"/>.
    /// An invalid kind is a protocol error: the message is invalid.
    /// </summary>
    /// <param name="logger"></param>
    /// <param name="partyFullName"></param>
    /// <param name="logLevel"></param>
    /// <returns></returns>
    public bool CheckCreationTimeKind( IActivityLineEmitter logger, string partyFullName, LogLevel logLevel = LogLevel.Error )
    {
        Throw.CheckNotNullArgument( logger );
        if( CreationTime.Kind != DateTimeKind.Utc )
        {
            if( logLevel != LogLevel.None ) logger.Log( logLevel, $"Invalid nonce creation time kind '{CreationTime.Kind}' for '{partyFullName}'. It must be in UTC." );
            return false;
        }
        return true;
    }


}
