using CK.Cris;
using System;
using System.Threading.Tasks;

namespace CK.AppIdentity.Cris
{
    /// <summary>
    /// Strongly typed outgoing request of <typeparamref name="T"/> command.
    /// </summary>
    /// <typeparam name="T">Type of the command.</typeparam>
    public interface ICommandRequest<T> : IOutgoingRequest where T : class, IAbstractCommand
    {
        /// <summary>
        /// Offers strongly types for the both the command and its result.
        /// This must be called only for <see cref="ICommand{TResult}"/> otherwise
        /// an <see cref="ArgumentException"/> is thrown.
        /// </summary>
        /// <typeparam name="TResult">The expected result type.</typeparam>
        public interface WithResult<TResult> : ICommandRequest<T>
        {
            /// <summary>
            /// Gets a task that is completed with a successful result or with an exception
            /// if <see cref="IOutgoingRequest.RequestCompletion"/> is a <see cref="ICrisResultError"/>.
            /// </summary>
            Task<TResult> Result { get; }
        }

        /// <summary>
        /// Gets the command.
        /// </summary>
        T Command { get; }

        /// <summary>
        /// Gets the validation result of the command computed by the callee.
        /// When this <see cref="CommandValidationResult.Success"/> is false,
        /// the <see cref="Completion"/> contains a <see cref="ICrisResultError"/> with the <see cref="CommandValidationResult.Errors"/>
        /// lines. 
        /// </summary>
        Task<CommandValidationResult> ValidationResult { get; }

        /// <summary>
        /// Gets the events that have been generated by the command execution.
        /// </summary>
        ICollector<IOutgoingRequest, IEvent> Events { get; }
    }
}
