using CK.Core;
using CK.Cris;
using System;
using System.Threading.Tasks;

namespace CK.AppIdentity.Cris;

/// <summary>
/// Carries the <see cref="Payload"/>, the <see cref="ValidationResult"/> and the eventual <see cref="RequestCompletion"/>.
/// of a <see cref="ICommand"/>, <see cref="ICommand{TResult}"/> or <see cref="IEvent"/>.
/// <para>
/// This is the non generic interface of <see cref="IOutgoingCommand{T}"/>.
/// </para>
/// </summary>
public interface IOutgoingCrisPoco
{
    /// <summary>
    /// Gets the <see cref="ICommand"/>, <see cref="ICommand{TResult}"/> or <see cref="IEvent"/>.
    /// </summary>
    ICrisPoco Payload { get; }

    /// <summary>
    /// Gets a token that identifies the initialization of this request.
    /// </summary>
    ActivityMonitor.Token IssuerToken { get; }

    /// <summary>
    /// Gets the UTC date and time creation of this request.
    /// </summary>
    DateTime CreationDate { get; }

    /// <summary>
    /// Gets a task that is completed when this request has been sent.
    /// </summary>
    Task<DateTime> SentDate { get; }

    /// <summary>
    /// Gets the validation result of the request computed by the callee.
    /// When this <see cref="CrisValidationResult.Success"/> is false,
    /// the <see cref="Completion"/> contains a <see cref="ICrisResultError"/> with the <see cref="CrisValidationResult.Errors"/>
    /// lines. 
    /// </summary>
    Task<CrisValidationResult> ValidationResult { get; }

    /// <summary>
    /// Gets a task that is completed when the request is terminated.
    /// The task's value can be:
    /// <list type="bullet">
    ///  <item>A <see cref="ICrisResultError"/> on validation or execution error by the callee.</item>
    ///  <item>A successful null result on success when <see cref="Payload"/> is a <see cref="ICommand"/> or a <see cref="IEvent"/>.</item>
    ///  <item>A successful result object if Payload is a <see cref="ICommand{TResult}"/>.</item>
    /// </list>
    /// </summary>
    Task<object?> RequestCompletion { get; }

    /// <summary>
    /// Gets the events that have been generated by the command execution/event distribution.
    /// </summary>
    ICollector<IOutgoingCrisPoco, IEvent> Events { get; }

}
