<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.11.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0-preview.3.23174.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0-preview-20230223-05" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
    <PackageReference Include="CK.Testing.Monitoring" Version="7.1.2--0023-develop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CK.AppIdentity\CK.AppIdentity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestStore\#Debug\LaToulousaine\%24SignatureBox\" />
    <Folder Include="TestStore\#Debug\LaToulousaine\%24Trolley1\" />
    <Folder Include="TestStore\#Debug\LaToulousaine\%24Trolley2\" />
    <Folder Include="TestStore\#Development\AllInOneInc\%24ControlBox\" />
    <Folder Include="TestStore\#Development\AllInOneInc\%24Hall1Trolley\" />
    <Folder Include="TestStore\#Development\AllInOneInc\%24Hall1Wall\" />
    <Folder Include="TestStore\#Development\AllInOneInc\%24Hall2Trolley\" />
    <Folder Include="TestStore\#Development\AllInOneInc\%24Hall2Wall\" />
    <Folder Include="TestStore\#Development\FakeDomain\%24FakeApp\%24Local\" />
    <Folder Include="TestStore\#Development\FakeDomain\%24SomeDynamicRemote\" />
    <Folder Include="TestStore\#Development\OneCS-SaaS\%24LogTower\" />
    <Folder Include="TestStore\#Development\OneCS-SaaS\%24OneCS1\%24Local\" />
    <Folder Include="TestStore\#Development\OpalCorp\%24ControlBox\" />
    <Folder Include="TestStore\#Development\OpalCorp\%24MeasureStation\" />
    <Folder Include="TestStore\#Development\SaaSProduct\%24SaaS1\%24Local\" />
    <Folder Include="TestStore\#Production\D\%24MyApp\%24Local\" />
    <Folder Include="TestStore\#Production\D\%24Remote1\" />
    <Folder Include="TestStore\#Production\D\%24Remote2\" />
  </ItemGroup>


</Project>
