using CK.Core;
using CK.Cris;
using System;

namespace CK.Cris
{
    /// <summary>
    /// A endpoint viewed by a <see cref="CrisExecutor{T}"/>.
    /// An instance of this class must be provided by the endpoint to the <see cref="CrisExecutor{T}.Execute(ICrisExecutorEndPoint{T}, T)"/>
    /// method.
    /// </summary>
    /// <typeparam name="T">The request type for this endpoint.</typeparam>
    public interface ICrisExecutorEndPoint<T> where T : CrisExecutorCommand
    {
        /// <summary>
        /// Must configure the interceptor. This is called before a request is handled.
        /// Errors and warnings must be emitted to the monitor: they will be mapped in
        /// a <see cref="CrisValidationResult"/>.
        /// </summary>
        /// <param name="monitor">The monitor into which errors and warnings must be emitted.</param>
        /// <param name="request">The request about to be handled.</param>
        /// <param name="services">The interceptor to configure.</param>
        void ConfigureServices( IActivityMonitor monitor, T request, SimpleServiceContainer services );

        /// <summary>
        /// Must send the validation result back to the caller.
        /// If <see cref="CrisValidationResult.Success"/> is false, the request handling is terminated.
        /// </summary>
        /// <param name="monitor">The monitor to use.</param>
        /// <param name="request">The handled request.</param>
        /// <param name="validationResult">The validation result.</param>
        void ReturnCrisValidationResult( IActivityMonitor monitor, T request, CrisValidationResult validationResult );

        /// <summary>
        /// Must send the event back to the caller (and may be to other parties).
        /// </summary>
        /// <param name="monitor">The monitor to use.</param>
        /// <param name="request">The currently handled request.</param>
        /// <param name="e">The event generated by the current request handling.</param>
        void ReturnEvent( IActivityMonitor monitor, T request, IEvent e );

        /// <summary>
        /// Must send the final result back to the caller.
        /// </summary>
        /// <param name="monitor">The monitor to use.</param>
        /// <param name="request">The handled request.</param>
        /// <param name="result">The result.</param>
        void ReturnCommandResult( IActivityMonitor monitor, T request, CrisExecutor.ICrisExecutorPayload? result );
    }
}
