using CK.Core;
using CK.Cris;
using System;
using System.Threading.Tasks;

namespace CK.AppIdentity.Cris
{
    /// <summary>
    /// A command request carries the <see cref="ValidationResult"/> and the eventual <see cref="Completion"/>
    /// of a command.
    /// This is the non generic and 
    /// </summary>
    public interface ICommandRequest
    {
        /// <summary>
        /// Gets the command.
        /// </summary>
        ICommand Command { get; }

        /// <summary>
        /// Gets the initial dependent token that initiates this request:
        /// this uniquely identifies this request.
        /// </summary>
        ActivityMonitor.DependentToken UniqueId { get; }

        /// <summary>
        /// Gets the UTC date and time creation of this request.
        /// </summary>
        DateTime CreationDate { get; }

        /// <summary>
        /// Gets whether this request has an authentication token that
        /// identifies a User or an Actor of the callee.
        /// </summary>
        bool HasAuthenticationToken { get; }

        /// <summary>
        /// Gets a task that is completed when this request has been sent.
        /// </summary>
        Task<DateTime> SentDate { get; }

        /// <summary>
        /// Gets the validation result of the command computed by the callee.
        /// When this <see cref="CommandValidationResult.Success"/> is false,
        /// the <see cref="Completion"/> contains a <see cref="ICrisResultError"/> with the <see cref="CommandValidationResult.Errors"/>
        /// lines. 
        /// </summary>
        Task<CommandValidationResult> ValidationResult { get; }

        /// <summary>
        /// Gets a task that is completed with a non null <see cref="ICrisResultError"/>
        /// if the validation or execution fails.
        /// </summary>
        Task<ICrisResultError?> Completion { get; }

        /// <summary>
        /// Gets the events that have been generated by the command execution.
        /// </summary>
        ICollector<ICommandRequest, ICrisEvent> Events { get; }
    }
}
