<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Required for the scoped span. -->
    <LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CK.AppIdentity.KeyManagement\CK.AppIdentity.KeyManagement.csproj" />
  </ItemGroup>

</Project>
